pnputil -i -a E:\Balloon\%1\amd64\*.inf
pnputil -i -a E:\NetKVM\%1\amd64\*.inf
pnputil -i -a E:\pvpanic\%1\amd64\*.inf
pnputil -i -a E:\qemupciserial\%1\amd64\*.inf
pnputil -i -a E:\qxldod\%1\amd64\*.inf
pnputil -i -a E:\vioinput\%1\amd64\*.inf
pnputil -i -a E:\viorng\%1\amd64\*.inf
pnputil -i -a E:\vioscsi\%1\amd64\*.inf
pnputil -i -a E:\vioserial\%1\amd64\*.inf
pnputil -i -a E:\viostor\%1\amd64\*.inf
